version: "3"

services:
    
    backend:
        build: ./backend
        ports:
           - "5000:5000"
        restart: always   

        depends_on:
            - db
        environment:
           DATABASE_URL: postgresql://postgres:sanketkadam09122003@db:5432/rag_assistant


    frontend:
        build: ./frontend
        ports:
            - "5173:5173"
        depends_on:
             - backend
        restart: always     

    db: 
       image: pgvector/pgvector:pg15
       container_name: rag_postgres
       restart: always
       environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: sanketkadam09122003
           POSTGRES_DB: rag_assistant
       ports:
          - "5432:5432"

       volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - pgdata:/var/lib/postgresql/data

volumes:
   pgdata:          


