"""initial schema

Revision ID: 8758a6805b7b
Revises: 
Create Date: 2026-04-07 12:31:25.868860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8758a6805b7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.alter_column('document_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('page_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('page_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('document_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
